//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class aa_business_pass
    {
        public int id { get; set; }
        public string mchid { get; set; }
        public string mchkey { get; set; }
        public string agentno { get; set; }
        public Nullable<int> type { get; set; }
        public string memo { get; set; }
        public Nullable<bool> enable { get; set; }
        public string pfxfile { get; set; }
        public string pfxpassword { get; set; }
        public string cerfile { get; set; }
        public string alipayappid { get; set; }
        public string rsaprivate { get; set; }
        public string rsapublic { get; set; }
        public Nullable<decimal> useamount { get; set; }
        public Nullable<decimal> dayamount { get; set; }
        public string reason { get; set; }
    }
}
