//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class fa_business_bank_card
    {
        public int id { get; set; }
        public Nullable<int> businessid { get; set; }
        public string mobileNo { get; set; }
        public string bankName { get; set; }
        public string name { get; set; }
        public string bankaccountNo { get; set; }
        public string certCode { get; set; }
        public string certNo { get; set; }
        public string defaultAcc { get; set; }
        public Nullable<bool> isaudit { get; set; }
        public string province { get; set; }
        public string city { get; set; }
        public string bankaddress { get; set; }
        public Nullable<System.DateTime> addtime { get; set; }
        public string adduser { get; set; }
        public Nullable<System.DateTime> updatetime { get; set; }
        public string updateuser { get; set; }
        public string bankCode { get; set; }
        public string bankEightCode { get; set; }
    }
}
