//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class fa_business_basic
    {
        public int id { get; set; }
        public string code { get; set; }
        public string password { get; set; }
        public Nullable<int> merchantid { get; set; }
        public string merchantName { get; set; }
        public string shortName { get; set; }
        public string handleType { get; set; }
        public string city { get; set; }
        public string merchantAddress { get; set; }
        public string servicePhone { get; set; }
        public string orgCode { get; set; }
        public string merchantType { get; set; }
        public string category { get; set; }
        public string corpmanName { get; set; }
        public string corpmanId { get; set; }
        public string corpmanPhone { get; set; }
        public string corpmanMobile { get; set; }
        public string corpmanEmail { get; set; }
        public string bankCode { get; set; }
        public string bankName { get; set; }
        public string bankaccountNo { get; set; }
        public string bankaccountName { get; set; }
        public string autoCus { get; set; }
        public string remark { get; set; }
        public string licenseNo { get; set; }
        public string taxRegisterNo { get; set; }
        public Nullable<int> agentid { get; set; }
        public string appId { get; set; }
        public string appSecret { get; set; }
        public Nullable<decimal> balance { get; set; }
        public Nullable<decimal> alipaybalance { get; set; }
        public Nullable<decimal> wechatbalance { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<bool> isaudit { get; set; }
        public Nullable<System.DateTime> addtime { get; set; }
        public string adduser { get; set; }
        public Nullable<System.DateTime> updatetime { get; set; }
        public string updateuser { get; set; }
        public string addrType { get; set; }
        public string contactType { get; set; }
        public string mcc { get; set; }
        public string licenseType { get; set; }
        public string contactMan { get; set; }
        public string telNo { get; set; }
        public string mobilePhone { get; set; }
        public string email { get; set; }
        public string licenseBeginDate { get; set; }
        public string licenseEndDate { get; set; }
        public string licenseRange { get; set; }
        public Nullable<System.DateTime> keyaddtime { get; set; }
        public string merchant_num { get; set; }
        public Nullable<decimal> ratio { get; set; }
        public Nullable<int> minAmount { get; set; }
        public Nullable<int> maxAmount { get; set; }
        public string disabletime { get; set; }
        public string enabletime { get; set; }
        public Nullable<decimal> depositratio { get; set; }
        public Nullable<int> businesspasstype { get; set; }
        public Nullable<decimal> wechatratio { get; set; }
        public Nullable<decimal> alipayratio { get; set; }
        public Nullable<decimal> unionratio { get; set; }
        public Nullable<decimal> freezeamount { get; set; }
        public Nullable<bool> isfreeze { get; set; }
        public string alipayaccount { get; set; }
    }
}
