//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class fa_open_payment
    {
        public int id { get; set; }
        public string merchantId { get; set; }
        public string handleType { get; set; }
        public string cycleValue { get; set; }
        public string busiCode { get; set; }
        public string futureRateType { get; set; }
        public string futureRateValue { get; set; }
        public string futureMinAmount { get; set; }
        public string futureMaxAmount { get; set; }
        public string agencyId { get; set; }
        public Nullable<int> wechat_status { get; set; }
        public Nullable<decimal> wechat_rate { get; set; }
        public Nullable<int> alipay_status { get; set; }
        public Nullable<decimal> alipay_rate { get; set; }
        public Nullable<int> daipay_status { get; set; }
        public Nullable<decimal> daipay_rate { get; set; }
        public Nullable<int> qqpay_status { get; set; }
        public Nullable<decimal> qqpay_rate { get; set; }
        public Nullable<int> jdpay_status { get; set; }
        public Nullable<decimal> jdpay_rate { get; set; }
        public Nullable<int> unionpay_status { get; set; }
        public Nullable<decimal> unionpay_rate { get; set; }
        public Nullable<bool> isaudit { get; set; }
        public Nullable<System.DateTime> addtime { get; set; }
        public string adduser { get; set; }
        public Nullable<System.DateTime> updatetime { get; set; }
        public string updateuser { get; set; }
    }
}
