//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class me_member
    {
        public int memberid { get; set; }
        public string phone { get; set; }
        public string alipayname { get; set; }
        public string alipayaccount { get; set; }
        public string wechatname { get; set; }
        public Nullable<bool> iswechat { get; set; }
        public Nullable<bool> isalipay { get; set; }
        public Nullable<decimal> alipayamount { get; set; }
        public Nullable<decimal> alipayuseamount { get; set; }
        public Nullable<decimal> wechatamount { get; set; }
        public Nullable<decimal> wechatuseamount { get; set; }
        public Nullable<bool> enable { get; set; }
        public Nullable<int> businessid { get; set; }
        public string userid { get; set; }
        public Nullable<System.DateTime> updatetime { get; set; }
        public string memo { get; set; }
    }
}
