//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelDb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ytfEntities : DbContext
    {
        public ytfEntities()
            : base("name=ytfEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<aa_bank_code> aa_bank_code { get; set; }
        public virtual DbSet<aa_business_balance> aa_business_balance { get; set; }
        public virtual DbSet<aa_business_category> aa_business_category { get; set; }
        public virtual DbSet<aa_business_coding> aa_business_coding { get; set; }
        public virtual DbSet<aa_business_pass> aa_business_pass { get; set; }
        public virtual DbSet<aa_business_type> aa_business_type { get; set; }
        public virtual DbSet<aa_merchant_city> aa_merchant_city { get; set; }
        public virtual DbSet<aa_platbase> aa_platbase { get; set; }
        public virtual DbSet<fa_business_bank_card> fa_business_bank_card { get; set; }
        public virtual DbSet<fa_business_basic> fa_business_basic { get; set; }
        public virtual DbSet<fa_business_merchant> fa_business_merchant { get; set; }
        public virtual DbSet<fa_open_payment> fa_open_payment { get; set; }
        public virtual DbSet<me_member> me_member { get; set; }
        public virtual DbSet<pay_task> pay_task { get; set; }
        public virtual DbSet<po_abnormalorder> po_abnormalorder { get; set; }
        public virtual DbSet<po_agentwithdraw> po_agentwithdraw { get; set; }
        public virtual DbSet<po_businessdateflow> po_businessdateflow { get; set; }
        public virtual DbSet<po_despoit> po_despoit { get; set; }
        public virtual DbSet<po_order> po_order { get; set; }
        public virtual DbSet<sh_business_appinfo> sh_business_appinfo { get; set; }
        public virtual DbSet<sh_business_balancelog> sh_business_balancelog { get; set; }
        public virtual DbSet<sh_business_bank_card> sh_business_bank_card { get; set; }
        public virtual DbSet<sh_business_commison> sh_business_commison { get; set; }
        public virtual DbSet<sh_business_replybalance> sh_business_replybalance { get; set; }
        public virtual DbSet<sy_admin> sy_admin { get; set; }
        public virtual DbSet<sy_agent> sy_agent { get; set; }
        public virtual DbSet<sy_agent_commission_audit> sy_agent_commission_audit { get; set; }
        public virtual DbSet<sy_agentratio> sy_agentratio { get; set; }
        public virtual DbSet<sy_merchant> sy_merchant { get; set; }
        public virtual DbSet<sy_mercommision> sy_mercommision { get; set; }
        public virtual DbSet<sy_qrcode> sy_qrcode { get; set; }
        public virtual DbSet<sy_role> sy_role { get; set; }
        public virtual DbSet<sy_router> sy_router { get; set; }
        public virtual DbSet<sy_routers> sy_routers { get; set; }
        public virtual DbSet<sy_tariff_management> sy_tariff_management { get; set; }
        public virtual DbSet<me_member_view> me_member_view { get; set; }
    
        public virtual int p_alipaydetail_add(Nullable<int> businessid, string name)
        {
            var businessidParameter = businessid.HasValue ?
                new ObjectParameter("businessid", businessid) :
                new ObjectParameter("businessid", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_alipaydetail_add", businessidParameter, nameParameter);
        }
    
        public virtual int p_auto_closealipay()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_auto_closealipay");
        }
    
        public virtual ObjectResult<PROC_Agentaddwithdraw_Result> PROC_Agentaddwithdraw(Nullable<int> agid, Nullable<decimal> commission)
        {
            var agidParameter = agid.HasValue ?
                new ObjectParameter("agid", agid) :
                new ObjectParameter("agid", typeof(int));
    
            var commissionParameter = commission.HasValue ?
                new ObjectParameter("commission", commission) :
                new ObjectParameter("commission", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_Agentaddwithdraw_Result>("PROC_Agentaddwithdraw", agidParameter, commissionParameter);
        }
    
        public virtual ObjectResult<PROC_AgentAuditwithdraw_Result> PROC_AgentAuditwithdraw(Nullable<int> id, string reason, string auditor, Nullable<int> status)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var reasonParameter = reason != null ?
                new ObjectParameter("reason", reason) :
                new ObjectParameter("reason", typeof(string));
    
            var auditorParameter = auditor != null ?
                new ObjectParameter("auditor", auditor) :
                new ObjectParameter("auditor", typeof(string));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_AgentAuditwithdraw_Result>("PROC_AgentAuditwithdraw", idParameter, reasonParameter, auditorParameter, statusParameter);
        }
    
        public virtual int PROC_Agentwithdrawlist(string begindate, string enddate, Nullable<int> status, string keyword, Nullable<int> page, Nullable<int> pagesize)
        {
            var begindateParameter = begindate != null ?
                new ObjectParameter("begindate", begindate) :
                new ObjectParameter("begindate", typeof(string));
    
            var enddateParameter = enddate != null ?
                new ObjectParameter("enddate", enddate) :
                new ObjectParameter("enddate", typeof(string));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(int));
    
            var keywordParameter = keyword != null ?
                new ObjectParameter("keyword", keyword) :
                new ObjectParameter("keyword", typeof(string));
    
            var pageParameter = page.HasValue ?
                new ObjectParameter("page", page) :
                new ObjectParameter("page", typeof(int));
    
            var pagesizeParameter = pagesize.HasValue ?
                new ObjectParameter("pagesize", pagesize) :
                new ObjectParameter("pagesize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_Agentwithdrawlist", begindateParameter, enddateParameter, statusParameter, keywordParameter, pageParameter, pagesizeParameter);
        }
    
        public virtual ObjectResult<PROC_Agentwithdrawlistbyagent_Result> PROC_Agentwithdrawlistbyagent(string begindate, string enddate, Nullable<int> agid, Nullable<int> status, Nullable<int> page, Nullable<int> pagesize)
        {
            var begindateParameter = begindate != null ?
                new ObjectParameter("begindate", begindate) :
                new ObjectParameter("begindate", typeof(string));
    
            var enddateParameter = enddate != null ?
                new ObjectParameter("enddate", enddate) :
                new ObjectParameter("enddate", typeof(string));
    
            var agidParameter = agid.HasValue ?
                new ObjectParameter("agid", agid) :
                new ObjectParameter("agid", typeof(int));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(int));
    
            var pageParameter = page.HasValue ?
                new ObjectParameter("page", page) :
                new ObjectParameter("page", typeof(int));
    
            var pagesizeParameter = pagesize.HasValue ?
                new ObjectParameter("pagesize", pagesize) :
                new ObjectParameter("pagesize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_Agentwithdrawlistbyagent_Result>("PROC_Agentwithdrawlistbyagent", begindateParameter, enddateParameter, agidParameter, statusParameter, pageParameter, pagesizeParameter);
        }
    
        public virtual ObjectResult<PROC_AuditOrderDepositByAgent_Result> PROC_AuditOrderDepositByAgent(string despoitno, Nullable<int> status, string reason)
        {
            var despoitnoParameter = despoitno != null ?
                new ObjectParameter("despoitno", despoitno) :
                new ObjectParameter("despoitno", typeof(string));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(int));
    
            var reasonParameter = reason != null ?
                new ObjectParameter("reason", reason) :
                new ObjectParameter("reason", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_AuditOrderDepositByAgent_Result>("PROC_AuditOrderDepositByAgent", despoitnoParameter, statusParameter, reasonParameter);
        }
    
        public virtual ObjectResult<PROC_AuditOrderDepositByNiuchao_Result> PROC_AuditOrderDepositByNiuchao(string despoitno, Nullable<int> status, string reason)
        {
            var despoitnoParameter = despoitno != null ?
                new ObjectParameter("despoitno", despoitno) :
                new ObjectParameter("despoitno", typeof(string));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(int));
    
            var reasonParameter = reason != null ?
                new ObjectParameter("reason", reason) :
                new ObjectParameter("reason", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_AuditOrderDepositByNiuchao_Result>("PROC_AuditOrderDepositByNiuchao", despoitnoParameter, statusParameter, reasonParameter);
        }
    
        public virtual int PROC_AutoReleaseFreeamount()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_AutoReleaseFreeamount");
        }
    
        public virtual ObjectResult<PROC_BusinessCheckBalance_Result> PROC_BusinessCheckBalance(Nullable<int> businessid)
        {
            var businessidParameter = businessid.HasValue ?
                new ObjectParameter("businessid", businessid) :
                new ObjectParameter("businessid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_BusinessCheckBalance_Result>("PROC_BusinessCheckBalance", businessidParameter);
        }
    
        public virtual ObjectResult<PROC_CheckBusinessBalance_Result> PROC_CheckBusinessBalance()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_CheckBusinessBalance_Result>("PROC_CheckBusinessBalance");
        }
    
        public virtual ObjectResult<PROC_CheckOrderStatus_Result> PROC_CheckOrderStatus(string orderno)
        {
            var ordernoParameter = orderno != null ?
                new ObjectParameter("orderno", orderno) :
                new ObjectParameter("orderno", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_CheckOrderStatus_Result>("PROC_CheckOrderStatus", ordernoParameter);
        }
    
        public virtual ObjectResult<PROC_CreateOrder_Result> PROC_CreateOrder(Nullable<decimal> amount, string remark, string appid, Nullable<int> paytype, Nullable<int> businesspasstype, string frontUrl)
        {
            var amountParameter = amount.HasValue ?
                new ObjectParameter("amount", amount) :
                new ObjectParameter("amount", typeof(decimal));
    
            var remarkParameter = remark != null ?
                new ObjectParameter("remark", remark) :
                new ObjectParameter("remark", typeof(string));
    
            var appidParameter = appid != null ?
                new ObjectParameter("appid", appid) :
                new ObjectParameter("appid", typeof(string));
    
            var paytypeParameter = paytype.HasValue ?
                new ObjectParameter("paytype", paytype) :
                new ObjectParameter("paytype", typeof(int));
    
            var businesspasstypeParameter = businesspasstype.HasValue ?
                new ObjectParameter("businesspasstype", businesspasstype) :
                new ObjectParameter("businesspasstype", typeof(int));
    
            var frontUrlParameter = frontUrl != null ?
                new ObjectParameter("frontUrl", frontUrl) :
                new ObjectParameter("frontUrl", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_CreateOrder_Result>("PROC_CreateOrder", amountParameter, remarkParameter, appidParameter, paytypeParameter, businesspasstypeParameter, frontUrlParameter);
        }
    
        public virtual ObjectResult<PROC_CreateOrderByPersonal_Result> PROC_CreateOrderByPersonal(Nullable<decimal> amount, string remark, string appid, Nullable<int> paytype, string frontUrl)
        {
            var amountParameter = amount.HasValue ?
                new ObjectParameter("amount", amount) :
                new ObjectParameter("amount", typeof(decimal));
    
            var remarkParameter = remark != null ?
                new ObjectParameter("remark", remark) :
                new ObjectParameter("remark", typeof(string));
    
            var appidParameter = appid != null ?
                new ObjectParameter("appid", appid) :
                new ObjectParameter("appid", typeof(string));
    
            var paytypeParameter = paytype.HasValue ?
                new ObjectParameter("paytype", paytype) :
                new ObjectParameter("paytype", typeof(int));
    
            var frontUrlParameter = frontUrl != null ?
                new ObjectParameter("frontUrl", frontUrl) :
                new ObjectParameter("frontUrl", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_CreateOrderByPersonal_Result>("PROC_CreateOrderByPersonal", amountParameter, remarkParameter, appidParameter, paytypeParameter, frontUrlParameter);
        }
    
        public virtual ObjectResult<PROC_CreateOrderByPersonalThird_Result> PROC_CreateOrderByPersonalThird(string orderno, Nullable<decimal> amount, string remark, string appid, string returnurl, Nullable<int> paytype, string frontUrl)
        {
            var ordernoParameter = orderno != null ?
                new ObjectParameter("orderno", orderno) :
                new ObjectParameter("orderno", typeof(string));
    
            var amountParameter = amount.HasValue ?
                new ObjectParameter("amount", amount) :
                new ObjectParameter("amount", typeof(decimal));
    
            var remarkParameter = remark != null ?
                new ObjectParameter("remark", remark) :
                new ObjectParameter("remark", typeof(string));
    
            var appidParameter = appid != null ?
                new ObjectParameter("appid", appid) :
                new ObjectParameter("appid", typeof(string));
    
            var returnurlParameter = returnurl != null ?
                new ObjectParameter("returnurl", returnurl) :
                new ObjectParameter("returnurl", typeof(string));
    
            var paytypeParameter = paytype.HasValue ?
                new ObjectParameter("paytype", paytype) :
                new ObjectParameter("paytype", typeof(int));
    
            var frontUrlParameter = frontUrl != null ?
                new ObjectParameter("frontUrl", frontUrl) :
                new ObjectParameter("frontUrl", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_CreateOrderByPersonalThird_Result>("PROC_CreateOrderByPersonalThird", ordernoParameter, amountParameter, remarkParameter, appidParameter, returnurlParameter, paytypeParameter, frontUrlParameter);
        }
    
        public virtual ObjectResult<PROC_CreateOrderByThird_Result> PROC_CreateOrderByThird(string orderno, Nullable<decimal> amount, string remark, string appid, string returnurl, Nullable<int> paytype, string frontUrl)
        {
            var ordernoParameter = orderno != null ?
                new ObjectParameter("orderno", orderno) :
                new ObjectParameter("orderno", typeof(string));
    
            var amountParameter = amount.HasValue ?
                new ObjectParameter("amount", amount) :
                new ObjectParameter("amount", typeof(decimal));
    
            var remarkParameter = remark != null ?
                new ObjectParameter("remark", remark) :
                new ObjectParameter("remark", typeof(string));
    
            var appidParameter = appid != null ?
                new ObjectParameter("appid", appid) :
                new ObjectParameter("appid", typeof(string));
    
            var returnurlParameter = returnurl != null ?
                new ObjectParameter("returnurl", returnurl) :
                new ObjectParameter("returnurl", typeof(string));
    
            var paytypeParameter = paytype.HasValue ?
                new ObjectParameter("paytype", paytype) :
                new ObjectParameter("paytype", typeof(int));
    
            var frontUrlParameter = frontUrl != null ?
                new ObjectParameter("frontUrl", frontUrl) :
                new ObjectParameter("frontUrl", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_CreateOrderByThird_Result>("PROC_CreateOrderByThird", ordernoParameter, amountParameter, remarkParameter, appidParameter, returnurlParameter, paytypeParameter, frontUrlParameter);
        }
    
        public virtual ObjectResult<PROC_CreateOrderCheck_Result> PROC_CreateOrderCheck(Nullable<decimal> amount, string appid, Nullable<int> paytype, Nullable<int> businesspasstype)
        {
            var amountParameter = amount.HasValue ?
                new ObjectParameter("amount", amount) :
                new ObjectParameter("amount", typeof(decimal));
    
            var appidParameter = appid != null ?
                new ObjectParameter("appid", appid) :
                new ObjectParameter("appid", typeof(string));
    
            var paytypeParameter = paytype.HasValue ?
                new ObjectParameter("paytype", paytype) :
                new ObjectParameter("paytype", typeof(int));
    
            var businesspasstypeParameter = businesspasstype.HasValue ?
                new ObjectParameter("businesspasstype", businesspasstype) :
                new ObjectParameter("businesspasstype", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_CreateOrderCheck_Result>("PROC_CreateOrderCheck", amountParameter, appidParameter, paytypeParameter, businesspasstypeParameter);
        }
    
        public virtual ObjectResult<PROC_CreateOrderCheckByThird_Result> PROC_CreateOrderCheckByThird(string orderno, Nullable<decimal> amount, string appid, Nullable<int> paytype)
        {
            var ordernoParameter = orderno != null ?
                new ObjectParameter("orderno", orderno) :
                new ObjectParameter("orderno", typeof(string));
    
            var amountParameter = amount.HasValue ?
                new ObjectParameter("amount", amount) :
                new ObjectParameter("amount", typeof(decimal));
    
            var appidParameter = appid != null ?
                new ObjectParameter("appid", appid) :
                new ObjectParameter("appid", typeof(string));
    
            var paytypeParameter = paytype.HasValue ?
                new ObjectParameter("paytype", paytype) :
                new ObjectParameter("paytype", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_CreateOrderCheckByThird_Result>("PROC_CreateOrderCheckByThird", ordernoParameter, amountParameter, appidParameter, paytypeParameter);
        }
    
        public virtual ObjectResult<PROC_CreateUserid_Result> PROC_CreateUserid(string phone, string userid)
        {
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            var useridParameter = userid != null ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_CreateUserid_Result>("PROC_CreateUserid", phoneParameter, useridParameter);
        }
    
        public virtual ObjectResult<PROC_CustomerAddDespoit_Result> PROC_CustomerAddDespoit(string customerappid, Nullable<decimal> amount, string bankno, Nullable<int> paytype, Nullable<int> businesspasstype)
        {
            var customerappidParameter = customerappid != null ?
                new ObjectParameter("customerappid", customerappid) :
                new ObjectParameter("customerappid", typeof(string));
    
            var amountParameter = amount.HasValue ?
                new ObjectParameter("amount", amount) :
                new ObjectParameter("amount", typeof(decimal));
    
            var banknoParameter = bankno != null ?
                new ObjectParameter("bankno", bankno) :
                new ObjectParameter("bankno", typeof(string));
    
            var paytypeParameter = paytype.HasValue ?
                new ObjectParameter("paytype", paytype) :
                new ObjectParameter("paytype", typeof(int));
    
            var businesspasstypeParameter = businesspasstype.HasValue ?
                new ObjectParameter("businesspasstype", businesspasstype) :
                new ObjectParameter("businesspasstype", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_CustomerAddDespoit_Result>("PROC_CustomerAddDespoit", customerappidParameter, amountParameter, banknoParameter, paytypeParameter, businesspasstypeParameter);
        }
    
        public virtual ObjectResult<PROC_CustomerAddDespoitCheck_Result> PROC_CustomerAddDespoitCheck(string customerappid, Nullable<decimal> amount, string bankno)
        {
            var customerappidParameter = customerappid != null ?
                new ObjectParameter("customerappid", customerappid) :
                new ObjectParameter("customerappid", typeof(string));
    
            var amountParameter = amount.HasValue ?
                new ObjectParameter("amount", amount) :
                new ObjectParameter("amount", typeof(decimal));
    
            var banknoParameter = bankno != null ?
                new ObjectParameter("bankno", bankno) :
                new ObjectParameter("bankno", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_CustomerAddDespoitCheck_Result>("PROC_CustomerAddDespoitCheck", customerappidParameter, amountParameter, banknoParameter);
        }
    
        public virtual int PROC_DespoitOrderList(string begindate, string enddate, Nullable<int> agid, Nullable<int> businessid, Nullable<int> status, Nullable<int> page, Nullable<int> pagesize, Nullable<int> businesspasstype)
        {
            var begindateParameter = begindate != null ?
                new ObjectParameter("begindate", begindate) :
                new ObjectParameter("begindate", typeof(string));
    
            var enddateParameter = enddate != null ?
                new ObjectParameter("enddate", enddate) :
                new ObjectParameter("enddate", typeof(string));
    
            var agidParameter = agid.HasValue ?
                new ObjectParameter("agid", agid) :
                new ObjectParameter("agid", typeof(int));
    
            var businessidParameter = businessid.HasValue ?
                new ObjectParameter("businessid", businessid) :
                new ObjectParameter("businessid", typeof(int));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(int));
    
            var pageParameter = page.HasValue ?
                new ObjectParameter("page", page) :
                new ObjectParameter("page", typeof(int));
    
            var pagesizeParameter = pagesize.HasValue ?
                new ObjectParameter("pagesize", pagesize) :
                new ObjectParameter("pagesize", typeof(int));
    
            var businesspasstypeParameter = businesspasstype.HasValue ?
                new ObjectParameter("businesspasstype", businesspasstype) :
                new ObjectParameter("businesspasstype", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_DespoitOrderList", begindateParameter, enddateParameter, agidParameter, businessidParameter, statusParameter, pageParameter, pagesizeParameter, businesspasstypeParameter);
        }
    
        public virtual ObjectResult<PROC_DespoitVoice_Result> PROC_DespoitVoice(Nullable<int> agid)
        {
            var agidParameter = agid.HasValue ?
                new ObjectParameter("agid", agid) :
                new ObjectParameter("agid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_DespoitVoice_Result>("PROC_DespoitVoice", agidParameter);
        }
    
        public virtual ObjectResult<PROC_GetAlipayConfig_Result> PROC_GetAlipayConfig(string out_trade_no)
        {
            var out_trade_noParameter = out_trade_no != null ?
                new ObjectParameter("out_trade_no", out_trade_no) :
                new ObjectParameter("out_trade_no", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_GetAlipayConfig_Result>("PROC_GetAlipayConfig", out_trade_noParameter);
        }
    
        public virtual ObjectResult<PROC_GetAppsecert_Result> PROC_GetAppsecert(string appid)
        {
            var appidParameter = appid != null ?
                new ObjectParameter("appid", appid) :
                new ObjectParameter("appid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_GetAppsecert_Result>("PROC_GetAppsecert", appidParameter);
        }
    
        public virtual ObjectResult<PROC_GetDespoitDetail_Result> PROC_GetDespoitDetail(string despoitno)
        {
            var despoitnoParameter = despoitno != null ?
                new ObjectParameter("despoitno", despoitno) :
                new ObjectParameter("despoitno", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_GetDespoitDetail_Result>("PROC_GetDespoitDetail", despoitnoParameter);
        }
    
        public virtual ObjectResult<PROC_GetMerchantbusiness_Result> PROC_GetMerchantbusiness(Nullable<int> merchantid)
        {
            var merchantidParameter = merchantid.HasValue ?
                new ObjectParameter("merchantid", merchantid) :
                new ObjectParameter("merchantid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_GetMerchantbusiness_Result>("PROC_GetMerchantbusiness", merchantidParameter);
        }
    
        public virtual ObjectResult<PROC_GetNotifyInfo_Result> PROC_GetNotifyInfo(string orderno)
        {
            var ordernoParameter = orderno != null ?
                new ObjectParameter("orderno", orderno) :
                new ObjectParameter("orderno", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_GetNotifyInfo_Result>("PROC_GetNotifyInfo", ordernoParameter);
        }
    
        public virtual ObjectResult<PROC_GetOrderDepositQuery_Result> PROC_GetOrderDepositQuery()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_GetOrderDepositQuery_Result>("PROC_GetOrderDepositQuery");
        }
    
        public virtual ObjectResult<PROC_GetOrderQuery_Result> PROC_GetOrderQuery()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_GetOrderQuery_Result>("PROC_GetOrderQuery");
        }
    
        public virtual ObjectResult<string> PROC_GetRealAppsecert(string appid)
        {
            var appidParameter = appid != null ?
                new ObjectParameter("appid", appid) :
                new ObjectParameter("appid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("PROC_GetRealAppsecert", appidParameter);
        }
    
        public virtual ObjectResult<PROC_GetSHappinfo_Result> PROC_GetSHappinfo(string orderno)
        {
            var ordernoParameter = orderno != null ?
                new ObjectParameter("orderno", orderno) :
                new ObjectParameter("orderno", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_GetSHappinfo_Result>("PROC_GetSHappinfo", ordernoParameter);
        }
    
        public virtual ObjectResult<PROC_GetUpdateOrder_Result> PROC_GetUpdateOrder(string orderno, Nullable<int> status, string reason)
        {
            var ordernoParameter = orderno != null ?
                new ObjectParameter("orderno", orderno) :
                new ObjectParameter("orderno", typeof(string));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(int));
    
            var reasonParameter = reason != null ?
                new ObjectParameter("reason", reason) :
                new ObjectParameter("reason", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_GetUpdateOrder_Result>("PROC_GetUpdateOrder", ordernoParameter, statusParameter, reasonParameter);
        }
    
        public virtual int PROC_GetUpdateOrderDeposit(string despoitno, Nullable<int> status, string reason)
        {
            var despoitnoParameter = despoitno != null ?
                new ObjectParameter("despoitno", despoitno) :
                new ObjectParameter("despoitno", typeof(string));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(int));
    
            var reasonParameter = reason != null ?
                new ObjectParameter("reason", reason) :
                new ObjectParameter("reason", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_GetUpdateOrderDeposit", despoitnoParameter, statusParameter, reasonParameter);
        }
    
        public virtual ObjectResult<PROC_GetUserinfo_Result> PROC_GetUserinfo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_GetUserinfo_Result>("PROC_GetUserinfo");
        }
    
        public virtual ObjectResult<PROC_OrderAddQrcode_Result> PROC_OrderAddQrcode(string token, string url, string mark_sell)
        {
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            var urlParameter = url != null ?
                new ObjectParameter("url", url) :
                new ObjectParameter("url", typeof(string));
    
            var mark_sellParameter = mark_sell != null ?
                new ObjectParameter("mark_sell", mark_sell) :
                new ObjectParameter("mark_sell", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_OrderAddQrcode_Result>("PROC_OrderAddQrcode", tokenParameter, urlParameter, mark_sellParameter);
        }
    
        public virtual ObjectResult<PROC_OrderCallBack_Result> PROC_OrderCallBack(string orderno, string payno, Nullable<int> status)
        {
            var ordernoParameter = orderno != null ?
                new ObjectParameter("orderno", orderno) :
                new ObjectParameter("orderno", typeof(string));
    
            var paynoParameter = payno != null ?
                new ObjectParameter("payno", payno) :
                new ObjectParameter("payno", typeof(string));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_OrderCallBack_Result>("PROC_OrderCallBack", ordernoParameter, paynoParameter, statusParameter);
        }
    
        public virtual int PROC_OrderList(string begindate, string enddate, Nullable<int> agid, Nullable<int> businessid, string keyword, Nullable<int> status, Nullable<int> page, Nullable<int> pagesize, Nullable<int> businesspasstype, Nullable<int> paytype, string time)
        {
            var begindateParameter = begindate != null ?
                new ObjectParameter("begindate", begindate) :
                new ObjectParameter("begindate", typeof(string));
    
            var enddateParameter = enddate != null ?
                new ObjectParameter("enddate", enddate) :
                new ObjectParameter("enddate", typeof(string));
    
            var agidParameter = agid.HasValue ?
                new ObjectParameter("agid", agid) :
                new ObjectParameter("agid", typeof(int));
    
            var businessidParameter = businessid.HasValue ?
                new ObjectParameter("businessid", businessid) :
                new ObjectParameter("businessid", typeof(int));
    
            var keywordParameter = keyword != null ?
                new ObjectParameter("keyword", keyword) :
                new ObjectParameter("keyword", typeof(string));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(int));
    
            var pageParameter = page.HasValue ?
                new ObjectParameter("page", page) :
                new ObjectParameter("page", typeof(int));
    
            var pagesizeParameter = pagesize.HasValue ?
                new ObjectParameter("pagesize", pagesize) :
                new ObjectParameter("pagesize", typeof(int));
    
            var businesspasstypeParameter = businesspasstype.HasValue ?
                new ObjectParameter("businesspasstype", businesspasstype) :
                new ObjectParameter("businesspasstype", typeof(int));
    
            var paytypeParameter = paytype.HasValue ?
                new ObjectParameter("paytype", paytype) :
                new ObjectParameter("paytype", typeof(int));
    
            var timeParameter = time != null ?
                new ObjectParameter("time", time) :
                new ObjectParameter("time", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_OrderList", begindateParameter, enddateParameter, agidParameter, businessidParameter, keywordParameter, statusParameter, pageParameter, pagesizeParameter, businesspasstypeParameter, paytypeParameter, timeParameter);
        }
    
        public virtual ObjectResult<PROC_OrderPayInfo_Result> PROC_OrderPayInfo(string orderno)
        {
            var ordernoParameter = orderno != null ?
                new ObjectParameter("orderno", orderno) :
                new ObjectParameter("orderno", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_OrderPayInfo_Result>("PROC_OrderPayInfo", ordernoParameter);
        }
    
        public virtual ObjectResult<PROC_OrderPersonalCallBack_Result> PROC_OrderPersonalCallBack(string token, string mark_sell, string order_id, Nullable<decimal> money)
        {
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            var mark_sellParameter = mark_sell != null ?
                new ObjectParameter("mark_sell", mark_sell) :
                new ObjectParameter("mark_sell", typeof(string));
    
            var order_idParameter = order_id != null ?
                new ObjectParameter("order_id", order_id) :
                new ObjectParameter("order_id", typeof(string));
    
            var moneyParameter = money.HasValue ?
                new ObjectParameter("money", money) :
                new ObjectParameter("money", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_OrderPersonalCallBack_Result>("PROC_OrderPersonalCallBack", tokenParameter, mark_sellParameter, order_idParameter, moneyParameter);
        }
    
        public virtual ObjectResult<PROC_OrderPersonPayInfo_Result> PROC_OrderPersonPayInfo(string orderno)
        {
            var ordernoParameter = orderno != null ?
                new ObjectParameter("orderno", orderno) :
                new ObjectParameter("orderno", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_OrderPersonPayInfo_Result>("PROC_OrderPersonPayInfo", ordernoParameter);
        }
    
        public virtual ObjectResult<PROC_OrderQueryQrcode_Result> PROC_OrderQueryQrcode(string token)
        {
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_OrderQueryQrcode_Result>("PROC_OrderQueryQrcode", tokenParameter);
        }
    
        public virtual int PROC_OrderSumList(string begindate, string enddate)
        {
            var begindateParameter = begindate != null ?
                new ObjectParameter("begindate", begindate) :
                new ObjectParameter("begindate", typeof(string));
    
            var enddateParameter = enddate != null ?
                new ObjectParameter("enddate", enddate) :
                new ObjectParameter("enddate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_OrderSumList", begindateParameter, enddateParameter);
        }
    
        public virtual ObjectResult<PROC_OrderUpdateByAdmin_Result> PROC_OrderUpdateByAdmin(string orderno, string panyno, string reason)
        {
            var ordernoParameter = orderno != null ?
                new ObjectParameter("orderno", orderno) :
                new ObjectParameter("orderno", typeof(string));
    
            var panynoParameter = panyno != null ?
                new ObjectParameter("panyno", panyno) :
                new ObjectParameter("panyno", typeof(string));
    
            var reasonParameter = reason != null ?
                new ObjectParameter("reason", reason) :
                new ObjectParameter("reason", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_OrderUpdateByAdmin_Result>("PROC_OrderUpdateByAdmin", ordernoParameter, panynoParameter, reasonParameter);
        }
    
        public virtual ObjectResult<PROC_PayPassAdd_Result> PROC_PayPassAdd(string alipayappid, string rsaprivate, string rsapublic, Nullable<decimal> dayamount, string memo)
        {
            var alipayappidParameter = alipayappid != null ?
                new ObjectParameter("alipayappid", alipayappid) :
                new ObjectParameter("alipayappid", typeof(string));
    
            var rsaprivateParameter = rsaprivate != null ?
                new ObjectParameter("rsaprivate", rsaprivate) :
                new ObjectParameter("rsaprivate", typeof(string));
    
            var rsapublicParameter = rsapublic != null ?
                new ObjectParameter("rsapublic", rsapublic) :
                new ObjectParameter("rsapublic", typeof(string));
    
            var dayamountParameter = dayamount.HasValue ?
                new ObjectParameter("dayamount", dayamount) :
                new ObjectParameter("dayamount", typeof(decimal));
    
            var memoParameter = memo != null ?
                new ObjectParameter("memo", memo) :
                new ObjectParameter("memo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_PayPassAdd_Result>("PROC_PayPassAdd", alipayappidParameter, rsaprivateParameter, rsapublicParameter, dayamountParameter, memoParameter);
        }
    
        public virtual int PROC_PayPassList(string keyword, Nullable<int> status, Nullable<int> page, Nullable<int> pagesize)
        {
            var keywordParameter = keyword != null ?
                new ObjectParameter("keyword", keyword) :
                new ObjectParameter("keyword", typeof(string));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(int));
    
            var pageParameter = page.HasValue ?
                new ObjectParameter("page", page) :
                new ObjectParameter("page", typeof(int));
    
            var pagesizeParameter = pagesize.HasValue ?
                new ObjectParameter("pagesize", pagesize) :
                new ObjectParameter("pagesize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_PayPassList", keywordParameter, statusParameter, pageParameter, pagesizeParameter);
        }
    
        public virtual ObjectResult<PROC_PayPassUpdate_Result> PROC_PayPassUpdate(Nullable<int> id, string alipayappid, string rsaprivate, string rsapublic, Nullable<decimal> dayamount, string memo, Nullable<bool> enable)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var alipayappidParameter = alipayappid != null ?
                new ObjectParameter("alipayappid", alipayappid) :
                new ObjectParameter("alipayappid", typeof(string));
    
            var rsaprivateParameter = rsaprivate != null ?
                new ObjectParameter("rsaprivate", rsaprivate) :
                new ObjectParameter("rsaprivate", typeof(string));
    
            var rsapublicParameter = rsapublic != null ?
                new ObjectParameter("rsapublic", rsapublic) :
                new ObjectParameter("rsapublic", typeof(string));
    
            var dayamountParameter = dayamount.HasValue ?
                new ObjectParameter("dayamount", dayamount) :
                new ObjectParameter("dayamount", typeof(decimal));
    
            var memoParameter = memo != null ?
                new ObjectParameter("memo", memo) :
                new ObjectParameter("memo", typeof(string));
    
            var enableParameter = enable.HasValue ?
                new ObjectParameter("enable", enable) :
                new ObjectParameter("enable", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_PayPassUpdate_Result>("PROC_PayPassUpdate", idParameter, alipayappidParameter, rsaprivateParameter, rsapublicParameter, dayamountParameter, memoParameter, enableParameter);
        }
    
        public virtual int PROC_SHBusinessAppinfoList(string keyword, Nullable<int> status, Nullable<int> page, Nullable<int> pagesize)
        {
            var keywordParameter = keyword != null ?
                new ObjectParameter("keyword", keyword) :
                new ObjectParameter("keyword", typeof(string));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(int));
    
            var pageParameter = page.HasValue ?
                new ObjectParameter("page", page) :
                new ObjectParameter("page", typeof(int));
    
            var pagesizeParameter = pagesize.HasValue ?
                new ObjectParameter("pagesize", pagesize) :
                new ObjectParameter("pagesize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_SHBusinessAppinfoList", keywordParameter, statusParameter, pageParameter, pagesizeParameter);
        }
    
        public virtual int proc_unionbusinessbalance(Nullable<int> businessid)
        {
            var businessidParameter = businessid.HasValue ?
                new ObjectParameter("businessid", businessid) :
                new ObjectParameter("businessid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_unionbusinessbalance", businessidParameter);
        }
    
        public virtual int PROC_UpdateBusinessBalance(string appid, Nullable<decimal> balance)
        {
            var appidParameter = appid != null ?
                new ObjectParameter("appid", appid) :
                new ObjectParameter("appid", typeof(string));
    
            var balanceParameter = balance.HasValue ?
                new ObjectParameter("balance", balance) :
                new ObjectParameter("balance", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_UpdateBusinessBalance", appidParameter, balanceParameter);
        }
    
        public virtual int PROC_UpdateBusinessWorkkey(Nullable<int> businessid, string key)
        {
            var businessidParameter = businessid.HasValue ?
                new ObjectParameter("businessid", businessid) :
                new ObjectParameter("businessid", typeof(int));
    
            var keyParameter = key != null ?
                new ObjectParameter("key", key) :
                new ObjectParameter("key", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_UpdateBusinessWorkkey", businessidParameter, keyParameter);
        }
    
        public virtual int PROC_UpdateOrderPayno(string orderno, string payno)
        {
            var ordernoParameter = orderno != null ?
                new ObjectParameter("orderno", orderno) :
                new ObjectParameter("orderno", typeof(string));
    
            var paynoParameter = payno != null ?
                new ObjectParameter("payno", payno) :
                new ObjectParameter("payno", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_UpdateOrderPayno", ordernoParameter, paynoParameter);
        }
    
        public virtual ObjectResult<Report_Business_balance_Result> Report_Business_balance()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Report_Business_balance_Result>("Report_Business_balance");
        }
    
        public virtual int report_businessorderamount(string begindate, string enddate, string keyword, Nullable<int> page, Nullable<int> pagesize)
        {
            var begindateParameter = begindate != null ?
                new ObjectParameter("begindate", begindate) :
                new ObjectParameter("begindate", typeof(string));
    
            var enddateParameter = enddate != null ?
                new ObjectParameter("enddate", enddate) :
                new ObjectParameter("enddate", typeof(string));
    
            var keywordParameter = keyword != null ?
                new ObjectParameter("keyword", keyword) :
                new ObjectParameter("keyword", typeof(string));
    
            var pageParameter = page.HasValue ?
                new ObjectParameter("page", page) :
                new ObjectParameter("page", typeof(int));
    
            var pagesizeParameter = pagesize.HasValue ?
                new ObjectParameter("pagesize", pagesize) :
                new ObjectParameter("pagesize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("report_businessorderamount", begindateParameter, enddateParameter, keywordParameter, pageParameter, pagesizeParameter);
        }
    
        public virtual ObjectResult<Report_GetBusinessDespoit_Result> Report_GetBusinessDespoit(string begindate, string enddate, string keyword)
        {
            var begindateParameter = begindate != null ?
                new ObjectParameter("begindate", begindate) :
                new ObjectParameter("begindate", typeof(string));
    
            var enddateParameter = enddate != null ?
                new ObjectParameter("enddate", enddate) :
                new ObjectParameter("enddate", typeof(string));
    
            var keywordParameter = keyword != null ?
                new ObjectParameter("keyword", keyword) :
                new ObjectParameter("keyword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Report_GetBusinessDespoit_Result>("Report_GetBusinessDespoit", begindateParameter, enddateParameter, keywordParameter);
        }
    
        public virtual int Report_GetBusinessTrade(string begindate, string enddate, string keyword)
        {
            var begindateParameter = begindate != null ?
                new ObjectParameter("begindate", begindate) :
                new ObjectParameter("begindate", typeof(string));
    
            var enddateParameter = enddate != null ?
                new ObjectParameter("enddate", enddate) :
                new ObjectParameter("enddate", typeof(string));
    
            var keywordParameter = keyword != null ?
                new ObjectParameter("keyword", keyword) :
                new ObjectParameter("keyword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Report_GetBusinessTrade", begindateParameter, enddateParameter, keywordParameter);
        }
    
        public virtual int Report_GetPlatTrade(string begindate, string enddate, string keywork)
        {
            var begindateParameter = begindate != null ?
                new ObjectParameter("begindate", begindate) :
                new ObjectParameter("begindate", typeof(string));
    
            var enddateParameter = enddate != null ?
                new ObjectParameter("enddate", enddate) :
                new ObjectParameter("enddate", typeof(string));
    
            var keyworkParameter = keywork != null ?
                new ObjectParameter("keywork", keywork) :
                new ObjectParameter("keywork", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Report_GetPlatTrade", begindateParameter, enddateParameter, keyworkParameter);
        }
    
        public virtual int report_ordersuccessrate(string begindate, string enddate, string keyword, Nullable<int> page, Nullable<int> pagesize, Nullable<int> paytype)
        {
            var begindateParameter = begindate != null ?
                new ObjectParameter("begindate", begindate) :
                new ObjectParameter("begindate", typeof(string));
    
            var enddateParameter = enddate != null ?
                new ObjectParameter("enddate", enddate) :
                new ObjectParameter("enddate", typeof(string));
    
            var keywordParameter = keyword != null ?
                new ObjectParameter("keyword", keyword) :
                new ObjectParameter("keyword", typeof(string));
    
            var pageParameter = page.HasValue ?
                new ObjectParameter("page", page) :
                new ObjectParameter("page", typeof(int));
    
            var pagesizeParameter = pagesize.HasValue ?
                new ObjectParameter("pagesize", pagesize) :
                new ObjectParameter("pagesize", typeof(int));
    
            var paytypeParameter = paytype.HasValue ?
                new ObjectParameter("paytype", paytype) :
                new ObjectParameter("paytype", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("report_ordersuccessrate", begindateParameter, enddateParameter, keywordParameter, pageParameter, pagesizeParameter, paytypeParameter);
        }
    
        public virtual ObjectResult<report_payaccountorderamount_Result> report_payaccountorderamount(string begindate, string enddate, Nullable<int> page, Nullable<int> pagesize)
        {
            var begindateParameter = begindate != null ?
                new ObjectParameter("begindate", begindate) :
                new ObjectParameter("begindate", typeof(string));
    
            var enddateParameter = enddate != null ?
                new ObjectParameter("enddate", enddate) :
                new ObjectParameter("enddate", typeof(string));
    
            var pageParameter = page.HasValue ?
                new ObjectParameter("page", page) :
                new ObjectParameter("page", typeof(int));
    
            var pagesizeParameter = pagesize.HasValue ?
                new ObjectParameter("pagesize", pagesize) :
                new ObjectParameter("pagesize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<report_payaccountorderamount_Result>("report_payaccountorderamount", begindateParameter, enddateParameter, pageParameter, pagesizeParameter);
        }
    
        public virtual ObjectResult<PROC_OrderAlipayRedlCallBack_Result> PROC_OrderAlipayRedlCallBack(string token, string userid, string mark_sell, string order_id, Nullable<decimal> money)
        {
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            var useridParameter = userid != null ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(string));
    
            var mark_sellParameter = mark_sell != null ?
                new ObjectParameter("mark_sell", mark_sell) :
                new ObjectParameter("mark_sell", typeof(string));
    
            var order_idParameter = order_id != null ?
                new ObjectParameter("order_id", order_id) :
                new ObjectParameter("order_id", typeof(string));
    
            var moneyParameter = money.HasValue ?
                new ObjectParameter("money", money) :
                new ObjectParameter("money", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_OrderAlipayRedlCallBack_Result>("PROC_OrderAlipayRedlCallBack", tokenParameter, useridParameter, mark_sellParameter, order_idParameter, moneyParameter);
        }
    
        public virtual ObjectResult<PROC_OrderAlipayRedPayInfo_Result> PROC_OrderAlipayRedPayInfo(string orderno)
        {
            var ordernoParameter = orderno != null ?
                new ObjectParameter("orderno", orderno) :
                new ObjectParameter("orderno", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_OrderAlipayRedPayInfo_Result>("PROC_OrderAlipayRedPayInfo", ordernoParameter);
        }
    }
}
