//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class pay_task
    {
        public int id { get; set; }
        public Nullable<int> money { get; set; }
        public string url { get; set; }
        public string channel { get; set; }
        public string task_extra { get; set; }
        public string result_extra { get; set; }
        public string mark_sell { get; set; }
        public string mark_buy { get; set; }
        public string order_id { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> apply_time { get; set; }
        public Nullable<System.DateTime> creat_time { get; set; }
        public Nullable<System.DateTime> end_time { get; set; }
        public string apply_ip { get; set; }
        public string desp { get; set; }
        public byte[] tx { get; set; }
        public string phone { get; set; }
    }
}
