//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class po_agentwithdraw
    {
        public int id { get; set; }
        public Nullable<int> agid { get; set; }
        public Nullable<decimal> lastcommission { get; set; }
        public Nullable<decimal> newcommission { get; set; }
        public Nullable<decimal> commission { get; set; }
        public Nullable<int> status { get; set; }
        public string reason { get; set; }
        public Nullable<System.DateTime> addtime { get; set; }
        public string adduser { get; set; }
        public Nullable<System.DateTime> updatetime { get; set; }
        public string updateuser { get; set; }
    }
}
