//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class po_despoit
    {
        public int id { get; set; }
        public string despoitno { get; set; }
        public Nullable<int> businessid { get; set; }
        public Nullable<int> merchantid { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<int> agid { get; set; }
        public string appsecret { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<decimal> charge { get; set; }
        public string reason { get; set; }
        public string bankaccountno { get; set; }
        public string bankusername { get; set; }
        public string bankname { get; set; }
        public string bankcode { get; set; }
        public string bankeightcode { get; set; }
        public Nullable<System.DateTime> addtime { get; set; }
        public string adduser { get; set; }
        public Nullable<System.DateTime> audittime { get; set; }
        public Nullable<decimal> realamount { get; set; }
        public string mobileno { get; set; }
        public string bankaddress { get; set; }
        public Nullable<int> paytype { get; set; }
        public string certno { get; set; }
        public string province { get; set; }
        public string city { get; set; }
        public Nullable<int> businesspasstype { get; set; }
    }
}
