//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class po_order
    {
        public int id { get; set; }
        public Nullable<int> agid { get; set; }
        public string agname { get; set; }
        public Nullable<int> merchantid { get; set; }
        public string merchantname { get; set; }
        public Nullable<int> businessid { get; set; }
        public string businessname { get; set; }
        public string orderno { get; set; }
        public string thirdorderno { get; set; }
        public string payno { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<decimal> platfee { get; set; }
        public string auth_code { get; set; }
        public Nullable<decimal> commission { get; set; }
        public Nullable<decimal> servicecharge { get; set; }
        public string status { get; set; }
        public Nullable<int> paytype { get; set; }
        public string remark { get; set; }
        public string reason { get; set; }
        public Nullable<System.DateTime> addtime { get; set; }
        public string adduser { get; set; }
        public string returnurl { get; set; }
        public Nullable<bool> isnotify { get; set; }
        public Nullable<int> notifystatus { get; set; }
        public Nullable<int> notifycount { get; set; }
        public string notifyid { get; set; }
        public Nullable<System.DateTime> notifytime { get; set; }
        public Nullable<bool> ischeck { get; set; }
        public Nullable<int> businesspasstype { get; set; }
        public string account { get; set; }
        public string fronturl { get; set; }
        public Nullable<bool> isokcheck { get; set; }
        public Nullable<int> sh_businessid { get; set; }
        public string sh_storename { get; set; }
        public string alipayaccount { get; set; }
        public string checkstatus { get; set; }
        public string checkamount { get; set; }
        public Nullable<bool> ispersonali { get; set; }
        public Nullable<System.DateTime> creat_time { get; set; }
        public Nullable<System.DateTime> end_time { get; set; }
        public string qrcode { get; set; }
        public string phone { get; set; }
        public string userid { get; set; }
        public Nullable<bool> isscan { get; set; }
        public Nullable<System.DateTime> scantime { get; set; }
    }
}
