//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class sh_business_appinfo
    {
        public int id { get; set; }
        public string sh_appid { get; set; }
        public string sh_appsecret { get; set; }
        public string sh_storeid { get; set; }
        public string sh_storename { get; set; }
        public string sh_businessname { get; set; }
        public string sh_mobile { get; set; }
        public string sh_password { get; set; }
        public Nullable<decimal> sh_balance { get; set; }
        public Nullable<decimal> sh_commission { get; set; }
        public Nullable<decimal> sh_commratio { get; set; }
        public Nullable<int> agid { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<bool> isused { get; set; }
    }
}
