//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class sy_admin
    {
        public int userid { get; set; }
        public string usercode { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public Nullable<int> roleid { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> addtime { get; set; }
        public string adduser { get; set; }
        public Nullable<System.DateTime> updatetime { get; set; }
        public string updateuser { get; set; }
    }
}
