//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class sy_agent
    {
        public int id { get; set; }
        public string name { get; set; }
        public string password { get; set; }
        public string account_name { get; set; }
        public string card_number { get; set; }
        public string bank_accounts { get; set; }
        public string opening_address { get; set; }
        public string opening_point { get; set; }
        public Nullable<int> agency_level { get; set; }
        public Nullable<bool> direct_identity { get; set; }
        public string agent_rights { get; set; }
        public Nullable<decimal> agency_amount { get; set; }
        public Nullable<System.DateTime> agency_expiration_date { get; set; }
        public Nullable<System.DateTime> last_login_time { get; set; }
        public Nullable<int> user_status { get; set; }
        public string remarks { get; set; }
        public string corporate_name { get; set; }
        public string province { get; set; }
        public string city { get; set; }
        public string area { get; set; }
        public string industry_owned { get; set; }
        public string main_business { get; set; }
        public Nullable<int> company_number { get; set; }
        public Nullable<decimal> annual_turnover { get; set; }
        public string contacts { get; set; }
        public string contact_number { get; set; }
        public string mobile_phone { get; set; }
        public string qq_number { get; set; }
        public string mail_box { get; set; }
        public string proof_document { get; set; }
        public string company_logo { get; set; }
        public Nullable<bool> is_alipay { get; set; }
        public Nullable<bool> is_jd { get; set; }
        public Nullable<bool> is_t0 { get; set; }
        public Nullable<decimal> ratio { get; set; }
        public Nullable<decimal> commission { get; set; }
        public Nullable<System.DateTime> addtime { get; set; }
        public string adduser { get; set; }
        public Nullable<System.DateTime> updatetime { get; set; }
        public string updateuser { get; set; }
        public string domain { get; set; }
        public string bus_domain { get; set; }
    }
}
