//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class sy_merchant
    {
        public int id { get; set; }
        public string name { get; set; }
        public string password { get; set; }
        public int agid { get; set; }
        public Nullable<int> user_status { get; set; }
        public Nullable<bool> user_rights { get; set; }
        public string merchant_name { get; set; }
        public string province { get; set; }
        public string city { get; set; }
        public string area { get; set; }
        public string merchant_address { get; set; }
        public string contacts { get; set; }
        public string contact_information { get; set; }
        public string mail_box { get; set; }
        public string qq_number { get; set; }
        public Nullable<System.DateTime> expiration_date { get; set; }
        public Nullable<System.DateTime> last_login_time { get; set; }
        public Nullable<decimal> payment_limit { get; set; }
        public Nullable<decimal> recharge_limit { get; set; }
        public string appid { get; set; }
        public string appsecret { get; set; }
        public string returnurl { get; set; }
        public string disabletime { get; set; }
        public string enabletime { get; set; }
        public Nullable<System.DateTime> addtime { get; set; }
        public string adduser { get; set; }
        public Nullable<System.DateTime> updatetime { get; set; }
        public string updateuser { get; set; }
        public Nullable<decimal> comm_amount { get; set; }
        public Nullable<decimal> comm_ratio { get; set; }
        public string company_logo { get; set; }
        public string domain { get; set; }
    }
}
