//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class sy_mercommision
    {
        public int id { get; set; }
        public Nullable<int> merchantid { get; set; }
        public Nullable<int> agid { get; set; }
        public Nullable<decimal> comm_amount { get; set; }
        public Nullable<int> orderid { get; set; }
        public Nullable<int> type { get; set; }
        public string memo { get; set; }
        public Nullable<System.DateTime> addtime { get; set; }
        public string adduser { get; set; }
    }
}
