//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class sy_tariff_management
    {
        public int id { get; set; }
        public int agid { get; set; }
        public Nullable<decimal> wechat_platform_rate { get; set; }
        public Nullable<decimal> wechat_profit_margin { get; set; }
        public Nullable<decimal> wechat_division_rate { get; set; }
        public Nullable<decimal> alipay_platform_rate { get; set; }
        public Nullable<decimal> alipay_profit_margin { get; set; }
        public Nullable<decimal> alipay_division_rate { get; set; }
        public Nullable<decimal> jd_platform_rate { get; set; }
        public Nullable<decimal> jd_profit_margin { get; set; }
        public Nullable<decimal> jd_division_rate { get; set; }
        public Nullable<decimal> h5_platform_rate { get; set; }
        public Nullable<decimal> h5_profit_margin { get; set; }
        public Nullable<decimal> h5_division_rate { get; set; }
        public Nullable<System.DateTime> addtime { get; set; }
        public string adduser { get; set; }
        public Nullable<System.DateTime> updatetime { get; set; }
        public string updateuser { get; set; }
    }
}
